"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: foxglove
  IDL file: foxglove.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import foxglove


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Inner(idl.IdlStruct, typename="foxglove.Inner"):
    a: types.uint32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Outer(idl.IdlStruct, typename="foxglove.Outer"):
    inners: types.sequence['foxglove.Inner']


